// <auto-generated />
namespace Cook_Lagbe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BuaLagbeChangetoCookLagbe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BuaLagbeChangetoCookLagbe));
        
        string IMigrationMetadata.Id
        {
            get { return "202304251834545_BuaLagbeChangetoCookLagbe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
