//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bua_Lagbe.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payment_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public int payment_amount { get; set; }
        public int user_id { get; set; }
        public int cook_id { get; set; }
    
        public virtual Cook Cook { get; set; }
        public virtual User User { get; set; }
    }
}
